name: Pull Request Checks

on:
  pull_request:
    branches: [ main, develop ]

env:
  FLUTTER_VERSION: '3.24.0'

jobs:
  pr-checks:
    name: PR Quality Checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze code
        run: flutter analyze

      - name: Run tests with coverage
        run: flutter test --coverage

      - name: Check for breaking changes
        run: |
          if git diff --name-only origin/main...HEAD | grep -E "(pubspec\.yaml|lib/.*\.dart)" > /dev/null; then
            echo "Code changes detected - running additional checks"
            flutter pub deps
          fi

      - name: Comment PR with test results
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            let comment = '## 🔍 PR Quality Check Results\n\n';
            
            // Add test results if available
            try {
              const testOutput = await exec.getExecOutput('flutter', ['test', '--reporter=json']);
              comment += '✅ Tests passed\n';
            } catch (error) {
              comment += '❌ Tests failed\n';
            }
            
            comment += '\n📊 Coverage report will be available after merge.';
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

  build-check:
    name: Build Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --debug

      - name: Build Web
        run: flutter build web

      - name: Check APK size
        run: |
          APK_SIZE=$(stat -c%s build/app/outputs/flutter-apk/app-debug.apk)
          echo "APK Size: $(($APK_SIZE / 1024 / 1024)) MB"
          
          # Warn if APK is larger than 50MB
          if [ $APK_SIZE -gt 52428800 ]; then
            echo "⚠️ Warning: APK size is larger than 50MB"
          fi
